USE Labo11
GO
	INSERT INTO Fruits.Fruit (Nom, Couleur)
	VALUES
	('ananas', 'marron'),
	('avocat', 'vert'),
	('baie de goji', 'route'),
	('banane', 'jaune'),
	('bergamote', 'vert'),
	('carambole', 'jaune'),
	('cassis', 'noir'),
	('cerise', 'rouge'),
	('citron', 'jaune'),
	('canneberge', 'rouge'),
	('fraise', 'rouge'),
	('fruit de la passion', 'violet'),
	('fruit du dragon', 'rouge'),
	('grenade', 'rouge'),
	('kaki', 'orange'),
	('kiwaï', 'vert'),
	('kiwi', 'marron'),
	('kumquat', 'orange'),
	('litchi', 'rouge'),
	('noix de coco', 'marron'),
	('orange', 'orange'),
	('pain de singe', 'marron'),
	('poire', 'vert'),
	('pomme', 'rouge'),
	('abricot', 'orange'),
	('abricot pays', 'marron'),
	('açaï', 'noir'),
	('acérola', 'rouge'),
	('achacha', 'orange'),
	('aguaje', 'marron'),
	('airelle rouge', 'rouge'),
	('amia', 'vert'),
	('arbouse', 'rouge'),
	('aronia', 'noir'),
	('asiminier tribolé', 'vert'),
	('atte', 'vert'),
	('awara', 'orange'),
	('babaco', 'jaune'),
	('bael', 'vert'),
	('baie d''argousier', 'orange'),
	('abrbadine', 'jaune'),
	('bigarade', 'orange'),
	('bignay', 'rouge'),
	('bilimbi', 'vert'),
	('cacao', 'marron'),
	('calamondin', 'orange'),
	('canistel', 'jaune'),
	('cédrat', 'jaune'),
	('cempedak', 'vert'),
	('cenelle', 'rouge'),
	('chérimole', 'vert'),
	('chèvrefeuille bleu', 'bleu'),
	('cocona', 'orange'),
	('coeur de boeuf', 'rouge'),
	('coing', 'jaune'),
	('combava', 'vert'),
	('corossol', 'vert'),
	('cynorhodon', 'rouge'),
	('datte', 'marron'),
	('durian', 'vert'),
	('feijoas', 'vert'),
	('figue', 'violet'),
	('framboise', 'rouge'),
	('fruit à pain', 'vert'),
	('fruit miracle', 'rouge'),
	('goyave', 'vert'),
	('grenadelle', 'orange'),
	('griotte', 'rouge'),
	('groseille', 'rouge'),
	('icaque', 'rose'),
	('jaboticaba', 'noir'),
	('jacque', 'vert'),
	('jagua', 'marron'),
	('jamalac', 'rouge'),
	('jamblon', 'violet'),
	('jujube', 'marron'),
	('kiwano', 'orange'),
	('logane', 'beige'),
	('longkong', 'beige'),
	('luo han guo', 'marron'),
	('main de bouddha', 'jaune'),
	('mandarine', 'orange'),
	('mangoustan', 'marron'),
	('mangue', 'rouge'),
	('melon', 'vert'),
	('micocoule', 'marron'),
	('mikan', 'orange'),
	('mirabelle', 'rouge'),
	('mûre', 'noir'),
	('myrobolan', 'rouge'),
	('myrtille', 'bleu'),
	('narangille', 'nashi'),
	('nashi', 'orange'),
	('nèfle', 'marron'),
	('papaye', 'vert'),
	('pastèque', 'vert'),
	('pêche', 'orange'),
	('prune', 'violet'),
	('raisin', 'violet'),
	('sapote blanche', 'beige');
	